// Copyright 2026 net4n6-dev
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by scripts/catalogs/refresh-fips.go. DO NOT EDIT.
//
// Generated: 2026-05-29T14:19:44Z
// Generator: refresh-fips.go v1
// Sources:
//   - NIST CMVP (manual watchlist)
// Watchlist: watchlists/fips.yaml
//
// Refresh: run `make refresh-catalogs` and commit the diff.

package scoring

import "strings"

// fipsStarterMap lists library name+version prefixes known to have
// FIPS 140-2/140-3 validated builds. Match is by (lowercased library_name,
// version prefix via strings.HasPrefix). Generated from watchlists/fips.yaml.
var fipsStarterMap = []struct {
	LibraryName   string
	VersionPrefix string
	Note          string
	FIPSLevel     string
	Source        string
}{
	{LibraryName: "aws-cloudhsm", VersionPrefix: "*", Note: "[hsm] AWS CloudHSM PKCS#11 client (Luna-backed, FIPS 140-3 Level 3)", FIPSLevel: "fips140-3-l3", Source: "manual"},
	{LibraryName: "aws-lc", VersionPrefix: "1.", Note: "AWS-LC 1.x FIPS 140-3 validated (CMVP #4631)", FIPSLevel: "fips140-3-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4631"},
	{LibraryName: "aws-lc-fips", VersionPrefix: "2.", Note: "AWS-LC-FIPS 2.x FIPS 140-3 (CMVP #4759)", FIPSLevel: "fips140-3-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4759"},
	{LibraryName: "azure-keyvault", VersionPrefix: "*", Note: "[hsm] Azure Key Vault Premium HSM FIPS 140-2 Level 2 (Managed HSM L3)", FIPSLevel: "fips140-2-l2", Source: "manual"},
	{LibraryName: "boringcrypto", VersionPrefix: "*", Note: "Google BoringCrypto FIPS 140-2 (CMVP #3318 / FIPS 140-3 in progress)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3318"},
	{LibraryName: "bouncycastle-fips", VersionPrefix: "1.0.2.3", Note: "BC FIPS Java 1.0.2.3 (CMVP #3673)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3673"},
	{LibraryName: "bouncycastle-fips", VersionPrefix: "2.0.0", Note: "BC FIPS Java 2.0.0 (CMVP 140-3)", FIPSLevel: "fips140-3-l1", Source: "manual"},
	{LibraryName: "bouncycastle-fips", VersionPrefix: "2.0.3", Note: "BC FIPS Java 2.0.3", FIPSLevel: "fips140-3-l1", Source: "manual"},
	{LibraryName: "cryptocomply", VersionPrefix: "*", Note: "[commercial] SafeLogic CryptoComply FIPS 140-2 / 140-3", FIPSLevel: "fips140-2-l1", Source: "manual"},
	{LibraryName: "dell-bsafe", VersionPrefix: "*", Note: "[commercial] Dell BSAFE Crypto-J FIPS 140-2", FIPSLevel: "fips140-2-l1", Source: "manual"},
	{LibraryName: "entrust-nshield", VersionPrefix: "*", Note: "[hsm] Entrust nShield HSM FIPS 140-3 Level 3", FIPSLevel: "fips140-3-l3", Source: "manual"},
	{LibraryName: "ibm-jce", VersionPrefix: "11.", Note: "[java] IBM JCE 11 FIPS 140-3 (Semeru Runtimes)", FIPSLevel: "fips140-3-l1", Source: "manual"},
	{LibraryName: "ibm-jce", VersionPrefix: "8.", Note: "[java] IBM JCE 8 FIPS 140-2 (CMVP #2711)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/2711"},
	{LibraryName: "java-sunjce", VersionPrefix: "1.8.0_271", Note: "[java] JDK 8 SunJCE FIPS 140-2 (CMVP #3514)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3514"},
	{LibraryName: "java-sunjce", VersionPrefix: "11.0.9", Note: "[java] JDK 11 SunJCE FIPS 140-2 (CMVP #3672)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3672"},
	{LibraryName: "java-sunjce", VersionPrefix: "17.0.1", Note: "[java] JDK 17 SunJCE FIPS 140-3 (CMVP #4642)", FIPSLevel: "fips140-3-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4642"},
	{LibraryName: "java-sunjce", VersionPrefix: "21.0.1", Note: "[java] JDK 21 SunJCE FIPS 140-3 (CMVP #4846)", FIPSLevel: "fips140-3-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4846"},
	{LibraryName: "java-sunjce", VersionPrefix: "21.0.5", Note: "[java] JDK 21 SunJCE FIPS 140-3 later revision", FIPSLevel: "fips140-3-l1", Source: "manual"},
	{LibraryName: "java-sunjsse", VersionPrefix: "11.0.9", Note: "[java] JDK 11 SunJSSE FIPS 140-2 (CMVP #3672)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3672"},
	{LibraryName: "java-sunjsse", VersionPrefix: "17.0.1", Note: "[java] JDK 17 SunJSSE FIPS 140-3 (CMVP #4642)", FIPSLevel: "fips140-3-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4642"},
	{LibraryName: "libgcrypt", VersionPrefix: "1.10.", Note: "libgcrypt 1.10.x FIPS validated", FIPSLevel: "fips140-2-l1", Source: "manual"},
	{LibraryName: "libgcrypt", VersionPrefix: "1.8.5", Note: "RHEL 8 FIPS-validated libgcrypt (CMVP #3765)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3765"},
	{LibraryName: "mbedtls", VersionPrefix: "2.28.", Note: "Mbed TLS 2.28 LTS (FIPS builds via downstream; CMVP #4660)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4660"},
	{LibraryName: "mbedtls", VersionPrefix: "3.6.", Note: "Mbed TLS 3.6 LTS FIPS builds", FIPSLevel: "fips140-3-l1", Source: "manual"},
	{LibraryName: "microsoft-cng", VersionPrefix: "server2016", Note: "[windows] Microsoft CNG FIPS 140-2 (CMVP #2356)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/2356"},
	{LibraryName: "microsoft-cng", VersionPrefix: "server2019", Note: "[windows] Microsoft CNG FIPS 140-2 (CMVP #3197)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3197"},
	{LibraryName: "microsoft-cng", VersionPrefix: "server2022", Note: "[windows] Microsoft CNG FIPS 140-3 (CMVP #4536)", FIPSLevel: "fips140-3-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4536"},
	{LibraryName: "microsoft-cng", VersionPrefix: "win10-1809", Note: "[windows] Microsoft CNG FIPS 140-2 (CMVP #3197)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3197"},
	{LibraryName: "microsoft-cng", VersionPrefix: "win10-1903", Note: "[windows] Microsoft CNG FIPS 140-2 (CMVP #3197)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3197"},
	{LibraryName: "microsoft-cng", VersionPrefix: "win10-2004", Note: "[windows] Microsoft CNG FIPS 140-2 (CMVP #3644)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3644"},
	{LibraryName: "microsoft-cng", VersionPrefix: "win10-21h2", Note: "[windows] Microsoft CNG FIPS 140-3 (CMVP #4536)", FIPSLevel: "fips140-3-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4536"},
	{LibraryName: "microsoft-cng", VersionPrefix: "win11-22h2", Note: "[windows] Microsoft CNG FIPS 140-3 (CMVP #4491)", FIPSLevel: "fips140-3-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4491"},
	{LibraryName: "microsoft-cng", VersionPrefix: "win7", Note: "[windows] Microsoft CNG FIPS 140-2 (CMVP #1327)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/1327"},
	{LibraryName: "microsoft-cng", VersionPrefix: "win8.1", Note: "[windows] Microsoft CNG FIPS 140-2 (CMVP #2357)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/2357"},
	{LibraryName: "microsoft-rsaenh", VersionPrefix: "*", Note: "[windows] Microsoft RSA Enhanced CSP legacy FIPS (CMVP #560)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/560"},
	{LibraryName: "nss", VersionPrefix: "3.101", Note: "NSS ESR FIPS validated", FIPSLevel: "fips140-2-l1", Source: "manual"},
	{LibraryName: "nss", VersionPrefix: "3.112", Note: "NSS 3.112 ESR FIPS validated", FIPSLevel: "fips140-2-l1", Source: "manual"},
	{LibraryName: "nss", VersionPrefix: "3.79", Note: "NSS ESR FIPS validated (CMVP #4594)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4594"},
	{LibraryName: "nss", VersionPrefix: "3.90", Note: "NSS 3.90 ESR FIPS validated", FIPSLevel: "fips140-2-l1", Source: "manual"},
	{LibraryName: "openssl", VersionPrefix: "1.0.2k-fips", Note: "OpenSSL 1.0.2k-fips (RHEL 7 / CentOS 7; CMVP #1747)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/1747"},
	{LibraryName: "openssl", VersionPrefix: "1.0.2m-fips", Note: "OpenSSL 1.0.2m-fips (commercial FIPS build)", FIPSLevel: "fips140-2-l1", Source: "manual"},
	{LibraryName: "openssl", VersionPrefix: "1.0.2o-fips", Note: "OpenSSL 1.0.2o-fips", FIPSLevel: "fips140-2-l1", Source: "manual"},
	{LibraryName: "openssl", VersionPrefix: "1.0.2u-fips", Note: "OpenSSL 1.0.2u-fips (RHEL 7 later revision)", FIPSLevel: "fips140-2-l1", Source: "manual"},
	{LibraryName: "openssl", VersionPrefix: "1.1.1k-fips", Note: "OpenSSL 1.1.1k-fips (RHEL 8)", FIPSLevel: "fips140-2-l1", Source: "manual"},
	{LibraryName: "openssl", VersionPrefix: "3.0.0", Note: "OpenSSL 3.0 FIPS provider (CMVP #4282); requires explicit FIPS provider activation", FIPSLevel: "fips140-3-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4282"},
	{LibraryName: "openssl", VersionPrefix: "3.0.0-fips", Note: "OpenSSL 3.0.0 FIPS Provider; CMVP #4282", FIPSLevel: "fips140-3-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4282"},
	{LibraryName: "openssl", VersionPrefix: "3.0.7-fips", Note: "OpenSSL 3.0.7-fips (RHEL 9 / CMVP #4282)", FIPSLevel: "fips140-3-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4282"},
	{LibraryName: "openssl", VersionPrefix: "3.0.8", Note: "OpenSSL 3.0 FIPS provider later revision (CMVP #4282)", FIPSLevel: "fips140-3-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4282"},
	{LibraryName: "openssl", VersionPrefix: "3.0.8-fips", Note: "OpenSSL 3.0.8 FIPS Provider; CMVP #4685", FIPSLevel: "fips140-3-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4685"},
	{LibraryName: "openssl", VersionPrefix: "3.0.9-fips", Note: "OpenSSL 3.0.9-fips", FIPSLevel: "fips140-3-l1", Source: "manual"},
	{LibraryName: "openssl", VersionPrefix: "3.2.", Note: "OpenSSL 3.2 FIPS provider", FIPSLevel: "fips140-3-l1", Source: "manual"},
	{LibraryName: "openssl-fips", VersionPrefix: "2.0.16", Note: "OpenSSL FIPS Object Module 2.0 final (CMVP #1747)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/1747"},
	{LibraryName: "rsa-bsafe", VersionPrefix: "*", Note: "[commercial] RSA BSAFE Crypto-J FIPS 140-2 (Dell)", FIPSLevel: "fips140-2-l1", Source: "manual"},
	{LibraryName: "thales-luna", VersionPrefix: "*", Note: "[hsm] Thales Luna Network HSM 7 FIPS 140-3 Level 3", FIPSLevel: "fips140-3-l3", Source: "manual"},
	{LibraryName: "wolfssh", VersionPrefix: "1.4.15", Note: "wolfSSH FIPS 140-3 (uses wolfCrypt FIPS)", FIPSLevel: "fips140-3-l1", Source: "manual"},
	{LibraryName: "wolfssl", VersionPrefix: "4.7.0", Note: "wolfCrypt FIPS 140-2 (CMVP #3389)", FIPSLevel: "fips140-2-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3389"},
	{LibraryName: "wolfssl", VersionPrefix: "5.2.0", Note: "wolfCrypt FIPS 140-3", FIPSLevel: "fips140-3-l1", Source: "manual"},
	{LibraryName: "wolfssl", VersionPrefix: "5.6.0", Note: "wolfCrypt FIPS 140-3 later revision", FIPSLevel: "fips140-3-l1", Source: "manual"},
	{LibraryName: "wolfssl", VersionPrefix: "5.6.4", Note: "wolfCrypt FIPS 140-3 (CMVP #4718)", FIPSLevel: "fips140-3-l1", Source: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4718"},
	{LibraryName: "wolfssl", VersionPrefix: "5.7.0", Note: "wolfCrypt FIPS 140-3 later revision", FIPSLevel: "fips140-3-l1", Source: "manual"},
	{LibraryName: "wolfssl", VersionPrefix: "5.7.2", Note: "wolfCrypt FIPS 140-3 later revision", FIPSLevel: "fips140-3-l1", Source: "manual"},
	{LibraryName: "yubico-yubihsm", VersionPrefix: "*", Note: "[hsm] YubiHSM 2 FIPS 140-3 Level 3", FIPSLevel: "fips140-3-l3", Source: "manual"},
}

// Quiet unused-import warnings if no other code in this file uses strings.
var _ = strings.HasPrefix
