// Copyright 2026 net4n6-dev
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package scoring

import "strings"

// fipsVersionMatch reports whether a fipsStarterMap entry's version prefix
// matches the given version. "*" is the any-version sentinel used for
// product-level entries (HSMs, commercial closed-source) where no version
// prefix applies. Shared by checkLibraryFIPS and LibraryFIPSLevel.
func fipsVersionMatch(prefix, version string) bool {
	return prefix == "*" || strings.HasPrefix(version, prefix)
}

// LibraryFIPSLevel returns the FIPS validation level string for the given
// library + version, or empty string if not found. Used by
// internal/export/cbom to emit cdx:fips_validation_level per CDX 1.6.
// The fipsStarterMap data is generated by scripts/catalogs/refresh-fips.go;
// this lookup is hand-maintained.
func LibraryFIPSLevel(libraryName, version string) string {
	name := strings.ToLower(libraryName)
	for _, entry := range fipsStarterMap {
		if entry.LibraryName != name {
			continue
		}
		if fipsVersionMatch(entry.VersionPrefix, version) {
			return entry.FIPSLevel
		}
	}
	return ""
}
