// Copyright 2026 net4n6-dev
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package codegen emits Go source files for the catalog generators.
// All emitters route through here so output formatting is consistent
// (gofmt-compatible, deterministic ordering, canonical header).
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Header is the standard preamble emitted at the top of every generated file.
type Header struct {
	GeneratorName string   // e.g. "refresh-eol.go"
	Version       string   // e.g. "v1"
	Sources       []string // human-readable list of upstream sources
	Watchlist     string   // path to the watchlist YAML
	PackageName   string   // Go package
}

// Emit writes formatted Go source to outputPath atomically.
// Caller provides the body (struct/var declarations); Emit prepends the
// canonical header + go-generate marker + package declaration.
func Emit(outputPath string, header Header, body string) error {
	const apacheHeader = `// Copyright 2026 net4n6-dev
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
`
	var buf bytes.Buffer
	buf.WriteString(apacheHeader)
	fmt.Fprintf(&buf, "// Code generated by scripts/catalogs/%s. DO NOT EDIT.\n", header.GeneratorName)
	fmt.Fprintf(&buf, "//\n")
	fmt.Fprintf(&buf, "// Generated: %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&buf, "// Generator: %s %s\n", header.GeneratorName, header.Version)
	if len(header.Sources) > 0 {
		fmt.Fprintf(&buf, "// Sources:\n")
		for _, s := range header.Sources {
			fmt.Fprintf(&buf, "//   - %s\n", s)
		}
	}
	if header.Watchlist != "" {
		fmt.Fprintf(&buf, "// Watchlist: %s\n", header.Watchlist)
	}
	fmt.Fprintf(&buf, "//\n")
	fmt.Fprintf(&buf, "// Refresh: run `make refresh-catalogs` and commit the diff.\n")
	fmt.Fprintf(&buf, "\n")
	fmt.Fprintf(&buf, "package %s\n\n", header.PackageName)
	buf.WriteString(body)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt: %w\n--- raw output ---\n%s", err, buf.String())
	}

	// Atomic write via temp file + rename.
	dir := filepath.Dir(outputPath)
	tmp, err := os.CreateTemp(dir, ".catalog-gen-*.go")
	if err != nil {
		return fmt.Errorf("create temp: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName) // no-op if rename succeeded

	if _, err := tmp.Write(formatted); err != nil {
		tmp.Close()
		return fmt.Errorf("write temp: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temp: %w", err)
	}
	if err := os.Rename(tmpName, outputPath); err != nil {
		return fmt.Errorf("rename: %w", err)
	}
	return nil
}

// GoStringSlice emits a Go source representation of a string slice.
// Used for synonym lists. Sorted for deterministic output.
func GoStringSlice(items []string) string {
	if len(items) == 0 {
		return "nil"
	}
	var sb strings.Builder
	sb.WriteString("[]string{")
	for i, item := range items {
		if i > 0 {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%q", item)
	}
	sb.WriteString("}")
	return sb.String()
}
